<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>New Contact Form Submission</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 {
            color: #B8860B;
            border-bottom: 2px solid #B8860B;
            padding-bottom: 10px;
        }
        .message-container {
            background-color: #f9f9f9;
            border-left: 4px solid #B8860B;
            padding: 15px;
            margin: 20px 0;
        }
        .label {
            font-weight: bold;
            color: #555;
        }
    </style>
</head>
<body>
    <h1>New Contact Form Submission</h1>
    
    <p>You have received a new contact form submission from The District Tapas + Bar website.</p>
    
    <div>
        <p><span class="label">Name:</span> {{ $name }}</p>
        <p><span class="label">Email:</span> {{ $email }}</p>
        <p><span class="label">Phone:</span> {{ $phone }}</p>
        <p><span class="label">Subject:</span> {{ $subject }}</p>
    </div>
    
    <h2>Message:</h2>
    <div class="message-container">
        {{ $message }}
    </div>
    
    <p>You can reply directly to this email to respond to the customer.</p>
    
    <p>
        Regards,<br>
        The District Tapas + Bar Website
    </p>
    
    <hr>
    <p style="font-size: 12px; color: #777;">
        This email was automatically generated by the contact form on The District Tapas + Bar website.
    </p>
</body>
</html> 